version: '3'

services:
  db:
    image: postgres:10
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: db
    ports:
      - 5432:5432
    volumes:
      - "~/var/lib/postgres/10/data:/var/lib/postgresql/data"
  # adminer:
  #   image: adminer
  #   restart: always
  #   ports:
  #     - 8086:8080
